name: Test Runner

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Show current working directory
      - name: Show working dir
        run: echo "Current dir: $PWD"

      # Step 3: List files
      - name: List files
        run: dir

      # Step 4: Simple test
      - name: Test echo
        run: echo "Runner is working!"
